# get token
# POST http://localhost:8000/api/v1/auth/token
# Content-Type: application/x-www-form-urlencoded
# Accept: application/json

# username=rahul&password=pass123


# search flights (protected) - replace YOUR_ACCESS_TOKEN_HERE with the token returned from the previous request
POST http://localhost:8000/api/v1/flights/search
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJyYWh1bCIsImV4cCI6MTc2MTIwNjg5M30.j7fxDw9Vi1las2zz8Wy9LPp5BQHo5Z6HJ-3zG3_fy6M

{
	"EndUserIp": "1.2.3.4",
	"TokenId": "token_from_auth_or_placeholder",
	"AdultCount": 1,
	"ChildCount": 0,
	"InfantCount": 0,
	"DirectFlight": false,
	"OneStopFlight": false,
	"JourneyType": 1,
	"Segments": [
		{
			"Origin": "DEL",
			"Destination": "BOM",
			"FlightCabinClass": 2,
			"PreferredDepartureTime": "2025-11-01T09:00:00Z",
			"PreferredArrivalTime": "2025-11-01T11:00:00Z"
		}
	]
}