"""create airline and airports tables(fixed)

Revision ID: 8a849dd69c0a
Revises: 36c782605f68
Create Date: 2025-10-09 19:30:29.393161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a849dd69c0a'
down_revision: Union[str, Sequence[str], None] = '36c782605f68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airlines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_airlines'))
    )
    op.create_index(op.f('ix_airlines_code'), 'airlines', ['code'], unique=True)
    op.create_index(op.f('ix_airlines_id'), 'airlines', ['id'], unique=False)
    op.create_table('airports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_name', sa.String(length=100), nullable=False),
    sa.Column('city_code', sa.String(length=10), nullable=False),
    sa.Column('country_code', sa.String(length=10), nullable=False),
    sa.Column('country_name', sa.String(length=100), nullable=False),
    sa.Column('airport_code', sa.String(length=10), nullable=False),
    sa.Column('airport_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_airports'))
    )
    op.create_index(op.f('ix_airports_airport_code'), 'airports', ['airport_code'], unique=True)
    op.create_index(op.f('ix_airports_city_code'), 'airports', ['city_code'], unique=False)
    op.create_index(op.f('ix_airports_id'), 'airports', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_airports_id'), table_name='airports')
    op.drop_index(op.f('ix_airports_city_code'), table_name='airports')
    op.drop_index(op.f('ix_airports_airport_code'), table_name='airports')
    op.drop_table('airports')
    op.drop_index(op.f('ix_airlines_id'), table_name='airlines')
    op.drop_index(op.f('ix_airlines_code'), table_name='airlines')
    op.drop_table('airlines')
    # ### end Alembic commands ###
