 server {
    listen 80;              # nginx will listen on port 80 (default HTTP port)
    server_name _;  # specifies domain names this server block responds to (localhost in local setup)

    # / => means basically all requests    
    location / {
        # frontend build copied here
        root /usr/share/nginx/html;
        index index.html;
        # $uri => requested path
        # “Try to find the file the user requested,
        # and if you can’t find it, serve /index.html instead.”
        try_files $uri $uri/ /index.html;
    }

    # All requests starting with /api/ will be proxied to backend:8000
    location /api/v1/ {
        proxy_pass http://backend:8000;          # forward to backend container
        proxy_http_version 1.1;
        proxy_set_header Host $host;             # same as above
        proxy_set_header X-Real-IP $remote_addr; # same as above
    }
}
